# -*- coding: utf-8 -*-
"""Bing Moodboard

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NqhXBFs5fp_3Ba339A8Ljs7WgxCd1eZk
"""

pip install bing-image-downloader pillow

'''
Collecting bing-image-downloader
  Downloading bing_image_downloader-1.1.2-py3-none-any.whl (5.9 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (8.4.0)
Installing collected packages: bing-image-downloader
Successfully installed bing-image-downloader-1.1.2
'''

import os
from bing_image_downloader import downloader
from PIL import Image

event = input("Enter the event name: ")
theme = input("Enter the theme or keywords for the collage: ")

downloader.download(event + " " + theme, limit=8, output_dir='collage_images', adult_filter_off=True, force_replace=False, timeout=5)

canvas_width = 1000  
canvas_height = 800 
collage = Image.new("RGB", (canvas_width, canvas_height))

image_dir = "collage_images/" + event + " " + theme
image_paths = [os.path.join(image_dir, filename) for filename in os.listdir(image_dir)]

num_images = len(image_paths)
rows = int(num_images ** 0.5)
cols = int((num_images + rows - 1) / rows)


image_width = int(canvas_width / cols)
image_height = int(canvas_height / rows)

for idx, img_path in enumerate(image_paths):
    try:
        img = Image.open(img_path)
        img = img.resize((image_width, image_height), Image.ANTIALIAS)
        x = int(idx % cols) * image_width
        y = int(idx / cols) * image_height
        collage.paste(img, (x, y))
        print(f"Image {idx+1} added to the collage.")
    except Exception as e:
        print(f"Error adding image {idx+1} to the collage: {str(e)}")

collage.save("collage.jpg")
print("Collage created and saved as final_collage.jpg.")

'''
Enter the event name: marvel theme birthday party
Enter the theme or keywords for the collage: decor, food, cake
[%] Downloading Images to /content/collage_images/marvel theme birthday party decor, food, cake


[!!]Indexing page: 1

[%] Indexed 8 Images on Page 1.

===============================================

[%] Downloading Image #1 from https://i.pinimg.com/736x/f4/1f/4c/f41f4c6b9a70506049d3b841380f068d--marvel-cake-food-cakes.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/736x/fc/81/bd/fc81bde5190ee169dc7e164043224178.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://i.pinimg.com/736x/ff/61/80/ff6180b2da314cf14b7419f66f239a1e.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://birijus.com/wp-content/uploads/marvel-birthday-cakes-avengers-birthday-cake-marvel-hulk-ironman-captain-america-thor-www-728x971.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/originals/ed/28/74/ed2874ea826025cfb04ab667501d872b.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/originals/ed/ab/35/edab353261955e3866d5432b3a8dfd8f.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://cakescorner.in/wp-content/uploads/2020/07/Avengers-Theme-Cake-For-Kids-Cakescorner.in_.jpg
[%] File Downloaded !

[%] Downloading Image #8 from https://i.pinimg.com/originals/60/9f/60/609f6085941f5120f2d2d5b5fa6d32ad.jpg
[%] File Downloaded !



[%] Done. Downloaded 8 images.
Image 1 added to the collage.
Image 2 added to the collage.
Image 3 added to the collage.
Image 4 added to the collage.
Image 5 added to the collage.
Image 6 added to the collage.
Image 7 added to the collage.
Image 8 added to the collage.
Collage created and saved as final_collage.jpg.
'''