# -*- coding: utf-8 -*-
"""image downloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lqfEa97OXkQP4myhxEBnphgkJWSrmitP
"""

!pip install bing-image-downloader

!mkdir images

from bing_image_downloader import downloader
downloader.download("Hotel indoors for party daytime",limit=5,output_dir='images')

from bing_image_downloader import downloader
downloader.download("kids party themes",limit=1000,output_dir='images')

from bing_image_downloader import downloader
downloader.download("yacht party themes",limit=200,output_dir='images')

from bing_image_downloader import downloader
downloader.download("private party themes",limit=20,output_dir='images')

!pip install bing-image-downloader

from bing_image_downloader import downloader
downloader.download("private party themes",limit=2,output_dir='images')

from bing_image_downloader import downloader
downloader.download("corporate party themes",limit=200,output_dir='images')

from bing_image_downloader import downloader
downloader.download("private party themes",limit=2,output_dir='images')

from bing_image_downloader import downloader
downloader.download("kids party themes",limit=200,output_dir='images')

from bing_image_downloader import downloader
downloader.download("yacht party themes",limit=200,output_dir='images')

from bing_image_downloader import downloader
downloader.download("decoration",limit=1,output_dir='images')

from bing_image_downloader import downloader
downloader.download("decoration",limit=2,output_dir='images')

from google.colab import drive
drive.mount('/images')